# This is a simple example of using a config map to create a single page static site.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  # When the config map is mounted as a volume, these will be created as files.
  data:
  myvalue: {{ .Values.myvalue | quote }}
  test.txt: test
