{{- $fullName := .Release.Name -}}
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: {{ include "java-app.fullname" . }}-ingress
  labels:
    app: {{- include "java-app.labels" . | nindent 4 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "java-app.fullname" . }}-service-prod
            servicePort: 80
  - host: {{ .Values.ingress.stagehostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "java-app.fullname" . }}-service-stage
            servicePort: 80
