{{- $fullName := .Release.Name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charanapp.fullname" . }}-default-http-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{- include "java-app.selectorLabels" . | nindent 6 }}-default-http-backend
  template:
    metadata:
      labels:
        app: {{- include "java-app.labels" . | nindent 8 }}-default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ .Chart.Name }}-default-http-backend
        # Any image is permissable as long as:
        # 1. It serves a 404 page at /
        # 2. It serves 200 on a /healthz endpoint
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: name: {{ include "java-app.fullname" . }}-default-http-backend
spec:
  selector:
    app: {{- include "java-app.labels" . | nindent 4 }}-default-http-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8051
  type: ClusterIP
