{{- $fullName := .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}-lb
  labels:
  app: {{- include "java-app.labels" . | nindent 4 }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8051
      protocol: TCP
      name: http
  selector:
    app: {{- include "java-app.selectorLabels" . | nindent 4 }}
    release: {{ .Release.Name }}
    k8s-app: {{ include "java-app.fullname" . }}-nginx-ingress-lb
