{{- $fullName := .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}-service-prod
  labels:
    app: {{- include "java-app.labels" . | nindent 4 }}
    chart: {{- include "java-app.chart" . | nindent 4 }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    app: {{- include "java-app.selectorLabels" . | nindent 4 }}
    release: {{ .Release.Name }}
    slot: {{ .Values.productionSlot }}
