{{- $fullName := .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}-lb
  labels:
  app: {{- include "java-app.labels" . | nindent 4 }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    app: {{- include "java-app.selectorLabels" . | nindent 4 }}
    release: {{ .Release.Name }}
    k8s-app: {{ include "java-app.fullname" . }}-nginx-ingress-lb
