apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}-lb
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.loadbalancer.port }}
      targetPort: {{ .Values.loadbalancer.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "java-app.selectorLabels" . | nindent 4 }}
    k8s-app: {{ include "java-app.fullname" . }}-nginx-ingress-lb
