apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}-green
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.servicegreen.type }}
  ports:
    - port: {{ .Values.servicegreen.port }}
      targetPort: {{ .Values.servicegreen.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "java-app.selectorLabels" . | nindent 4 }}
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }} 
